// Generated by scripts/guardian/train-model.mjs. Do not edit by hand.
#pragma once
namespace guardian {
static constexpr unsigned int kModelVersion = 1;
static constexpr unsigned int kFeatureCount = 12;
static constexpr int kConfidenceThreshold = 9500;
static constexpr int kBiasMilli = -6712;
static constexpr int kCalibrationScaleMilli = 5976;
static constexpr int kCalibrationOffsetMilli = -3346;
static constexpr int kMinimumEvidence[kFeatureCount] = { 450, 900, 900, 500, 900, 500, 900, 900, 900, 900, 500, 900 };
static constexpr int kWeightsMilli[kFeatureCount] = { 4430, 1838, 4514, 2707, -6687, 3628, -6393, 3157, 1094, -3227, 1467, 3213 };
static constexpr int kKnotCount = 13;
static constexpr int kLogitKnotsMilli[kKnotCount] = { -12000, -10000, -8000, -6000, -4000, -2000, 0, 2000, 4000, 6000, 8000, 10000, 12000 };
static constexpr unsigned int kProbabilityKnots[kKnotCount] = { 0, 0, 0, 0, 0, 0, 340, 9998, 10000, 10000, 10000, 10000, 10000 };
}
