import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const rootDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const agent=[path.join(rootDir,'agent'),path.resolve(rootDir,'..')].find(p=>fs.existsSync(path.join(p,'extensions/pi-subagents/src/runs/shared/file-verification.ts')));
const {captureFileVerification,verifyFileContract,inspectStaticHtml,verifyObservedWriteScope} = await import(pathToFileURL(path.join(agent,'extensions/pi-subagents/src/runs/shared/file-verification.ts')));
const {expandCommonTask} = await import(pathToFileURL(path.join(agent,'extensions/pi-subagents/src/runs/shared/common-task.ts')));
const {validateAcceptanceInput,resolveEffectiveAcceptance,evaluateAcceptance,formatAcceptancePrompt} = await import(pathToFileURL(path.join(agent,'extensions/pi-subagents/src/runs/shared/acceptance.ts')));
const {buildCompletionDetails} = await import(pathToFileURL(path.join(agent,'extensions/pi-subagents/src/runs/background/notify.ts')));
const {normalizePublicSubagentExecution} = await import(pathToFileURL(path.join(agent,'extensions/pi-subagents/src/extension/public-execution.ts')));
const root=fs.mkdtempSync(path.join(os.tmpdir(),'pi-file-contract-'));
const write=(p,t)=>fs.writeFileSync(path.join(root,p),t);
const original='<h1>Title</h1><div>Body</div><script src="widget.js">const x="<div>";</script>';
try {
 const contract={scope:['index.html'],unchanged:['widget.js'],unchangedScripts:['index.html']};
 assert.deepEqual(validateAcceptanceInput({files:contract}),[]);
 const nativeWrite=(file,isError=false)=>[{role:'assistant',content:[{type:'toolCall',id:'w',name:'write',arguments:{path:file}}]},{role:'toolResult',toolCallId:'w',isError,content:[{type:'text',text:'written'}]}];
 assert.equal(verifyObservedWriteScope(contract,nativeWrite('outside.html'),root)[0].status,'failed');
 assert.equal(verifyObservedWriteScope(contract,nativeWrite('outside.html',true),root)[0].status,'not-applicable');
 assert.equal(verifyObservedWriteScope(contract,nativeWrite('index.html'),root)[0].status,'passed');
 assert.equal(verifyObservedWriteScope(contract,[],root)[0].status,'not-applicable');

 for(const files of [{scope:['../private']},{scope:['*.html']},{scope:['/etc/passwd']},{scope:[]},{scope:['a'],extra:true}]) assert.ok(validateAcceptanceInput({files}).length);
 write('index.html',original);write('widget.js','widget bytes');
 const baseline=captureFileVerification(contract,root);
 assert.ok(verifyFileContract(contract,baseline,root).every(c=>c.status==='passed'));
 assert.equal(verifyFileContract(contract,baseline,path.join(root,'missing-cwd'))[0].status,'failed','deleted execution directory must fail rather than skip contract');
 write('index.html','<div>Body</div></div><script src="widget.js">changed()</script>');write('widget.js','changed');
 const failed=verifyFileContract(contract,baseline,root);
 assert.match(failed.map(c=>c.message).join('\n'),/h1 count decreased/);
 assert.match(failed.map(c=>c.message).join('\n'),/new orphan <div>/);
 assert.match(failed.map(c=>c.message).join('\n'),/unchanged script blocks differ/);
 assert.match(failed.map(c=>c.message).join('\n'),/unchanged file bytes differ/);
 const acceptance=resolveEffectiveAcceptance({explicit:{level:'none',reason:'Independent bounded file checks only',files:contract},agentName:'worker',task:'Edit page'});
 const ledger=await evaluateAcceptance({acceptance,fileBaseline:baseline,cwd:root,output:'Everything tested and perfect. commandsRun: touch PROSE_MUST_NOT_RUN'});
 assert.equal(ledger.status,'rejected');
 const coverage=await evaluateAcceptance({acceptance:{...acceptance,files:undefined},cwd:root,task:'Edit index.html and preserve scripts',output:'all perfect'});
 assert.equal(coverage.runtimeChecks.find(c=>c.id==='file-contract:coverage').status,'not-applicable');
 const notification=buildCompletionDetails({agent:'worker',success:true,summary:'all perfect',results:[{agent:'worker',acceptance:coverage,output:'all perfect'}]});
 assert.match(notification.resultPreview,/not requested.*baseline/);
 assert.match(buildCompletionDetails({agent:'worker',success:false,results:[{agent:'worker',acceptance:ledger,output:'all perfect'}]}).resultPreview,/Independent file checks: FAILED/); assert.equal(fs.existsSync(path.join(root,'PROSE_MUST_NOT_RUN')),false);
 assert.match(formatAcceptancePrompt(acceptance),/Independent file checks/);
 assert.equal((await evaluateAcceptance({acceptance,cwd:root,output:'done'})).status,'rejected','missing baseline cannot pass');
 write('fragment.html','<div>fragment</div>');
 let c={scope:['fragment.html']}, b=captureFileVerification(c,root);
 write('fragment.html','<section>fragment</section>');
 assert.equal(verifyFileContract(c,b,root)[0].status,'passed','fragments do not require new h1');
 write('fragment.html','</div><div>old unclosed');b=captureFileVerification(c,root);
 assert.equal(verifyFileContract(c,b,root)[0].status,'passed','pre-existing balance errors are not blamed on worker');
 write('fragment.html','</div></div><div>old unclosed');assert.equal(verifyFileContract(c,b,root)[0].status,'failed');
 assert.deepEqual(inspectStaticHtml('<!-- <div></div></div> --><script>"<h1><div>"</script><style>/* <div> */</style><?php echo "<div>"; ?>').orphan,{});
 assert.equal(inspectStaticHtml('<!-- <h1> --><script>"<h1>"</script>').h1,0);
 c={scope:['new.html']};b=captureFileVerification(c,root);write('new.html','<div>new</div>');assert.equal(verifyFileContract(c,b,root)[0].status,'passed');
 fs.unlinkSync(path.join(root,'new.html'));assert.equal(verifyFileContract(c,b,root)[0].status,'failed');
 fs.symlinkSync(path.join(root,'index.html'),path.join(root,'link.html'));
 c={scope:['link.html']};b=captureFileVerification(c,root);assert.equal(verifyFileContract(c,b,root)[0].status,'failed');
 write('big.html','x'.repeat(1024*1024+1));c={scope:['big.html']};b=captureFileVerification(c,root);assert.match(verifyFileContract(c,b,root)[0].message,/byte limit/);
 const fan={commonTask:'SHARED',tasks:[{agent:'a',task:'A',acceptance:{files:{scope:['a.html']}}},{agent:'b',task:'B'}],async:true};
 const expanded=expandCommonTask(fan);assert.equal(normalizePublicSubagentExecution(fan).ok,true);assert.equal(normalizePublicSubagentExecution({chain:[{agent:'worker'}]}).ok,true);
 assert.equal(normalizePublicSubagentExecution({...fan,action:'status'}).ok,false);assert.equal(normalizePublicSubagentExecution({...fan,workflowScript:'x'}).ok,false);
 assert.equal(normalizePublicSubagentExecution({parallel:[]}).ok,false);
 assert.equal(fan.tasks[0].task,'A');assert.equal(expanded.commonTask,undefined);
 assert.ok(expanded.tasks.every(t=>(t.task.match(/SHARED/g)||[]).length===1));assert.equal(expandCommonTask(expanded),expanded);
 assert.equal(expanded.tasks[0].acceptance,fan.tasks[0].acceptance);
 const chain=expandCommonTask({commonTask:'SHARED',chain:[{agent:'a',task:'A'},{agent:'b'},{parallel:[{agent:'c',task:'C'}]},{expand:'x',parallel:{agent:'d',task:'{item}'}}]});
 assert.match(chain.chain[1].task,/\{previous\}/);assert.match(chain.chain[2].parallel[0].task,/SHARED/);assert.match(chain.chain[3].parallel.task,/\{item\}/);
 for(const input of [{commonTask:''},{commonTask:2,agent:'a'},{commonTask:'x',action:'status'},{commonTask:'x',workflowScript:'x'}]) assert.throws(()=>expandCommonTask(input));
 const scratch=path.join(os.tmpdir(),'pi-file-contract-helper-'+Date.now()+'.mjs');
 assert.equal(verifyObservedWriteScope(contract,nativeWrite(scratch),root)[0].status,'not-applicable','out-of-tree helper writes are unattributed, like shell writes');
 assert.equal(verifyObservedWriteScope(contract,nativeWrite('.pi/subagents/run.md'),root)[0].status,'not-applicable','harness artifact writes are unattributed runtime data');
 console.log('PASS: independent file baseline checks, bounds, scripts, fragments, missing baseline, native shared brief fan-out/chain normalization');
}finally{fs.rmSync(root,{recursive:true,force:true});}
