#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { makeGuardianCases } from "./case-data.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const HEADER = path.join(ROOT, "core/coding-agent/src/core/guardian/model-parameters.generated.h");
const MINIMUM_EVIDENCE = [450, 900, 900, 500, 900, 500, 900, 900, 900, 900, 500, 900];
const cases = makeGuardianCases();

function sigmoid(value) {
	if (value > 30) return 1;
	if (value < -30) return 0;
	return 1 / (1 + Math.exp(-value));
}

function fitLogistic(rows, iterations = 9000, learningRate = 0.08, regularization = 0.01) {
	const width = rows[0].features.length;
	const weights = Array(width).fill(0);
	let bias = 0;
	for (let step = 0; step < iterations; step++) {
		const gradient = Array(width).fill(0);
		let biasGradient = 0;
		for (const row of rows) {
			const values = row.features.map((value) => value / 1000);
			const probability = sigmoid(bias + values.reduce((sum, value, index) => sum + value * weights[index], 0));
			const error = probability - row.label;
			biasGradient += error;
			for (let index = 0; index < width; index++) gradient[index] += error * values[index];
		}
		const scale = learningRate / rows.length;
		bias -= scale * biasGradient;
		for (let index = 0; index < width; index++) {
			weights[index] -= scale * (gradient[index] + regularization * weights[index]);
		}
	}
	return { bias, weights };
}

function rawLogit(model, features) {
	return model.bias + features.reduce((sum, value, index) => sum + model.weights[index] * value / 1000, 0);
}

function fitPlatt(rows, model, iterations = 12000, learningRate = 0.025) {
	let scale = 1;
	let offset = 0;
	for (let step = 0; step < iterations; step++) {
		let scaleGradient = 0;
		let offsetGradient = 0;
		for (const row of rows) {
			const logit = rawLogit(model, row.features);
			const error = sigmoid(scale * logit + offset) - row.label;
			scaleGradient += error * logit;
			offsetGradient += error;
		}
		const rate = learningRate / rows.length;
		scale -= rate * scaleGradient;
		offset -= rate * offsetGradient;
	}
	return { scale, offset };
}

function metrics(rows, weights, bias, calibration) {
	let truePositive = 0;
	let falsePositive = 0;
	let trueNegative = 0;
	let falseNegative = 0;
	let brier = 0;
	let logLoss = 0;
	let admitted = 0;
	for (const row of rows) {
		const logit = bias + row.features.reduce((sum, value, index) => sum + weights[index] * value / 1000, 0);
		const probability = sigmoid(calibration.scale * logit + calibration.offset);
		const hardGated = row.features.every((value, index) => value >= MINIMUM_EVIDENCE[index]);
		const predicted = hardGated && probability >= 0.95;
		if (predicted) admitted++;
		if (predicted && row.label) truePositive++;
		else if (predicted) falsePositive++;
		else if (row.label) falseNegative++;
		else trueNegative++;
		brier += (probability - row.label) ** 2;
		const clipped = Math.max(1e-9, Math.min(1 - 1e-9, probability));
		logLoss += row.label ? -Math.log(clipped) : -Math.log(1 - clipped);
	}
	return {
		samples: rows.length,
		truePositive,
		falsePositive,
		trueNegative,
		falseNegative,
		precision: truePositive + falsePositive ? truePositive / (truePositive + falsePositive) : null,
		recall: truePositive + falseNegative ? truePositive / (truePositive + falseNegative) : null,
		brierScore: brier / rows.length,
		logLoss: logLoss / rows.length,
		admitted,
	};
}

const fitted = fitLogistic(cases.train);
const calibrated = fitPlatt(cases.calibration, fitted);
const weightsMilli = fitted.weights.map((weight) => Math.round(weight * 1000));
const biasMilli = Math.round(fitted.bias * 1000);
const calibrationScaleMilli = Math.round(calibrated.scale * 1000);
const calibrationOffsetMilli = Math.round(calibrated.offset * 1000);
const logitKnots = Array.from({ length: 13 }, (_, index) => -12000 + index * 2000);
const probabilities = logitKnots.map((knot) => Math.round(sigmoid((knot / 1000) * calibrated.scale + calibrated.offset) * 10000));
for (let i = 1; i < probabilities.length; i++) probabilities[i] = Math.max(probabilities[i], probabilities[i - 1]);

const header = `// Generated by scripts/guardian/train-model.mjs. Do not edit by hand.\n#pragma once\nnamespace guardian {\nstatic constexpr unsigned int kModelVersion = 1;\nstatic constexpr unsigned int kFeatureCount = ${cases.featureCount};\nstatic constexpr int kConfidenceThreshold = 9500;\nstatic constexpr int kBiasMilli = ${biasMilli};\nstatic constexpr int kCalibrationScaleMilli = ${calibrationScaleMilli};\nstatic constexpr int kCalibrationOffsetMilli = ${calibrationOffsetMilli};\nstatic constexpr int kMinimumEvidence[kFeatureCount] = { ${MINIMUM_EVIDENCE.join(", ")} };\nstatic constexpr int kWeightsMilli[kFeatureCount] = { ${weightsMilli.join(", ")} };\nstatic constexpr int kKnotCount = ${logitKnots.length};\nstatic constexpr int kLogitKnotsMilli[kKnotCount] = { ${logitKnots.join(", ")} };\nstatic constexpr unsigned int kProbabilityKnots[kKnotCount] = { ${probabilities.join(", ")} };\n}\n`;

if (process.argv.includes("--check")) {
	if (!fs.existsSync(HEADER) || fs.readFileSync(HEADER, "utf8") !== header) {
		console.error("Generated Guardian model header is stale. Run node scripts/guardian/train-model.mjs.");
		process.exitCode = 1;
	} else {
		console.log("Guardian model header is reproducible.");
	}
} else {
	fs.writeFileSync(HEADER, header);
	console.log(JSON.stringify({
		training: metrics(cases.train, fitted.weights, fitted.bias, { scale: 1, offset: 0 }),
		calibration: metrics(cases.calibration, fitted.weights, fitted.bias, calibrated),
		heldout: metrics(cases.heldout, fitted.weights, fitted.bias, calibrated),
		parameters: { biasMilli, weightsMilli, calibrationScaleMilli, calibrationOffsetMilli, probabilities },
	}, null, 2));
}
