import { Type, StringEnum } from '@earendil-works/pi-ai';
import { scoreContext, makeCapsule, type ContextItem } from './context-salience.ts';
import { evidenceCache } from './context-evidence.ts';
export function registerContextTools(pi: any, directory: () => string) {
  if (process.env.PI_CONTEXT_MEMORY === 'off') return;
  const output = (value: unknown) => ({ content: [{ type: 'text', text: JSON.stringify(value) }], details: value });
  const state = Type.String({ description: 'JSON array of {id,text,kind?,source?,timestamp?,unresolved?}. Kinds: goal,constraint,finding,decision,file,failure,next_action. <=1024 items.' });
  const parse = (s: string): ContextItem[] => { if (typeof s !== 'string' || s.length > 262144) throw Error('Items JSON exceeds 256 KiB.'); return JSON.parse(s); };
  pi.registerTool({ name: 'context_score', label: 'Context salience', description: 'Rank bounded context items locally by task relevance, freshness and provenance; protect goals, constraints, unresolved items and next actions. Scores are priorities, not calibrated ML probabilities.', parameters: Type.Object({ task: Type.String(), items: state }), async execute(_id: string, args: any, signal?: AbortSignal) { signal?.throwIfAborted(); const scored = scoreContext(parse(args.items), args.task); return output({ scores: scored.map(({ text, ...score }) => score), sourceItems: scored.length }); } });
  pi.registerTool({ name: 'handoff_capsule', label: 'Handoff capsule', description: 'Build an extractive goal/findings/decisions/files/failures/next_action capsule for a fresh subagent task. Include user constraints and unresolved items explicitly. Default 2200 character budget (~500 tokens for English only; not tokenizer guaranteed). Critical overflow rejects; originals remain authoritative. Pass capsule in subagent task rather than forking full history.', parameters: Type.Object({ goal: Type.String(), items: state, maxChars: Type.Optional(Type.Number()) }), async execute(_id: string, args: any, signal?: AbortSignal) { signal?.throwIfAborted(); return output(makeCapsule(parse(args.items), args.goal, args.maxChars ?? 2200)); } });
  pi.registerTool({ name: 'evidence_cache', label: 'Evidence cache', description: 'Store a tiny verbatim code/research-file observation with SHA256 provenance, or retrieve relevant unchanged observations from this active session branch. Local project sources only, <=256 KiB. Inferred claims are rejected; URL research must first exist in an attributable local source.', parameters: Type.Object({ action: StringEnum(['put', 'query']), source: Type.Optional(Type.String()), quote: Type.Optional(Type.String()), query: Type.Optional(Type.String()) }), async execute(_id: string, args: any, signal: AbortSignal, _update: any, ctx: any) { return output(await evidenceCache(directory(), { cwd: ctx.cwd, session: ctx.sessionManager.getSessionId(), head: ctx.sessionManager.getLeafId(), branch: (ctx.sessionManager.getBranch?.() ?? []).map((x: any) => x.id).filter(Boolean) }, args, signal)); } });
}
