import type { CodeSignal } from './code-guidance-signals.ts';
import { createHash } from 'node:crypto';
import { proseReport } from './code-quality.ts';

const UI_FILE = /\.(?:html?|css|scss|sass|less|jsx|tsx|vue|svelte|php)$/i;
const EXCLUDED = /(?:^|\/)(?:node_modules|vendor|dist|build|fixtures?|__fixtures__|skills|references)\/|\.(?:min|generated|test|spec)\.|(?:^|\/)SKILL\.md$/i;
/** Docs-shaped paths document internals legitimately; leakage cues skip them. */
const DOCS_PATH = /(?:^|\/)(?:docs?|documentation|api-reference|reference|changelog|architecture|adr|design-docs|specs?|guides?)\//i;
/** Policy pages legitimately explain privacy/security/accessibility postures. */
const POLICY_FILE = /(?:privacy|security|terms|legal|compliance|cookies?|accessibility)[\w.-]*\.(?:md|mdx|txt|html?|jsx|tsx|vue|svelte|php)$/i;
const LEAK_STRONG = /built with|powered by|made with|runs on|tech stack|under the hood|github\.com\/[\w.-]+\/|deployed (?:with|on|via)|CI\/CD pipeline|hosted on/i;
const DESIGN_LEAK = /design system|design tokens?|type scale|spacing scale|component library|our (?:typography|spacing|components)|8[ -]?pt (?:grid|spacing)/i;
const LEAK_WEAK = ['react','vue','angular','svelte','next.js','nuxt','tailwind','docker','kubernetes','sqlite','postgres','mongodb','redis','graphql','rest api','pipeline','schema','embeddings','orchestration','vercel','netlify','cloudflare workers','terraform','webpack','vite'];
const AI_PROVENANCE = /AI-powered|AI-assisted|written with AI|generated by AI|agent-generated|AI-generated|created (?:with|by) (?:AI|artificial intelligence)|with AI assistance/i;
const THEATER = /privacy by design|bank-level|military-grade|256-bit|WCAG|fully accessible|secured with (?:https|ssl|tls)|end-to-end encrypted|enterprise-grade security/i;
const BUZZWORDS = ['next-generation','state-of-the-art','world-class','best-in-class','revolutionary','cutting-edge','seamless','robust','scalable','innovative','intelligent','contextual','frictionless','holistic','synergy','synergies','game-changer','game-changing','supercharge','supercharges','unleash','elevate','empower','leverage','streamline','transformative'];
const SELF_PRAISE = /carefully curated|thoughtfully (?:designed|crafted)|meticulously (?:crafted|designed|curated)|elegantly (?:simple|designed|minimal)|beautifully (?:simple|minimal|clean)|with (?:great )?care and precision/i;
const MISSION = /our mission is|we'?re on a mission|we are on a mission|to revolutionize|to democratize|we believe the future/i;
const TRANSPARENCY_HEADING = /^(?:#{1,3}\s+|<h[1-3]\b[^>]*>)(?:how this (?:site|website|page) works|how it was built|our process|our methodology|methodology|site architecture|under the hood)\b/im;
const VAGUE_NAV_LABEL = 'insights|discover|explore|solutions|resources';
const TOUR = /guided tour|product tour|onboarding tour|welcome modal|take (?:the|a) tour|walkthrough (?:modal|overlay)/i;
const AI_WIDGET = /\bask ai\b|ai (?:assistant|chatbot)|ai chat\b|chat with (?:our )?ai/i;
const METRIC_BASIS = /measured|study|survey|benchmark|tested|based on|report|data|customers|teams/i;
/** The default AI-product palette: indigo/violet into purple/pink gradients,
 * as Tailwind stops or the stock hexes. A brand may own it; most do not. */
const STOCK_PALETTE = /\bfrom-(?:indigo|violet|purple|blue)-[3-7]00\b[^"'`\n]{0,80}\b(?:via|to)-(?:purple|fuchsia|pink|violet)-[3-7]00\b|(?:linear|radial|conic)-gradient\([^)]{0,160}#(?:6366f1|4f46e5|7c3aed|8b5cf6|a855f7)\b[^)]{0,160}#(?:a855f7|ec4899|d946ef|db2777|c026d3|8b5cf6)\b/i;
/** Section families of the stock landing template, in its usual order. */
const TEMPLATE_SECTIONS = [/trusted by|used by|loved by|as seen (?:in|on)|our (?:clients|partners)/i, /\bfeatures?\b|why (?:choose|us)|what we offer|benefits/i, /how it works|in (?:three|3) (?:simple )?steps|get started in/i, /testimonials?|what (?:our )?(?:customers|clients|users) say|reviews/i, /pricing|plans?\b/i, /\bfaq\b|frequently asked/i, /ready to (?:get started|begin|join)|get started today|join (?:thousands|us)|start your (?:free )?trial/i];
const wordRe = (w: string) => new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i');
const luminance = (hex: string) => {
  const full = hex.length === 3 ? [...hex].map(c=>c+c).join('') : hex;
  const rgb = [0,2,4].map(i=>parseInt(full.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);
  return rgb[0]*.2126 + rgb[1]*.7152 + rgb[2]*.0722;
};

/** Explicit tool check shares the edit-hook policy; absence of cues is not a pass. */
export function inspectUiSource(file: string, text: string) {
  const normalized = file.replaceAll('\\','/');
  if (typeof text !== 'string' || text.length > 24000) throw Error('UI source check requires at most 24000 characters; inspect a complete smaller component');
  const supported = UI_FILE.test(normalized) && !EXCLUDED.test(normalized);
  return { sourceHash:createHash('sha256').update(text).digest('hex'), status:supported?'inspected':'unsupported',
    findings:supported?slopGuidanceSignals(normalized,text,12):[],
    scope:'Bounded source cues only; no CSS cascade, rendering, interaction execution or visual certification. No findings does not mean good design.',
    next:'Inspect the complete component in its project design system, then verify rendered appearance and relevant interaction states.' };
}

/** Advisory checks of small authored changes. Never infer authorship or rewrite automatically. */
export function slopGuidanceSignals(file: string, value: unknown, limit = 3): CodeSignal[] {
  if (typeof value !== 'string' || value.length > 24000) return [];
  file = file.replaceAll('\\', '/');
  if (EXCLUDED.test(file)) return [];
  const ui = UI_FILE.test(file);
  // DOM-generating scripts (vanilla JS/TS builders, template literals) carry
  // markup structure but not authorial stylesheets: markup-shape cues apply,
  // CSS-property cues do not.
  const script = /\.[cm]?[jt]s$/i.test(file);
  const prose = /\.(?:md|mdx|txt|html?|jsx|tsx|vue|svelte|php)$/i.test(file);
  if (!ui && !prose && !script) return [];
  // Examples and comments are not authored product presentation.
  const text = value.replace(/```[\s\S]*?```|<!--[\s\S]*?-->|\/\*[\s\S]*?\*\//g,'').replace(/^\s*>.*$/gm,'').replace(/^\s*\/\/.*$/gm,'');
  const out: CodeSignal[] = [];
  if (ui || script) {
    const add = (key: string, check: string) => out.push({key, skill:'ui-antipattern-review', check});
    // Require a short markup region containing the label, enclosure and motion.
    // aria-live, a stock ticker, or a plain status label alone is not this pattern.
    for (const match of text.matchAll(/<(?:span|div|p)\b[^>]{0,500}>[\s\S]{0,900}?>\s*(?:live|online|real[ -]time)\s*<\//gi)) {
      const region = match[0];
      if (/\b(?:rounded-full|(?:status-)?pill|badge)\b/i.test(region)
          && /\b(?:animate-(?:ping|pulse)|blink\w*|puls(?:e|ing)[-_ ]?dot)\b/i.test(region)) {
        add('ui-live-pill', 'A live/status label, pill enclosure and blinking/pulsing treatment occur together. Remove this decorative status badge by default; prefer quiet, specific status text tied to observed state. If live activity is required, verify connected, stale, offline and reduced-motion states. A source cue cannot prove the status is fake.');
        break;
      }
    }
    if (/<(?:div|span)\b[^>]{0,800}\b(?:onClick|onclick|@click)\s*=/i.test(text))
      add('ui-clickable-container', 'A div/span has a click handler. Check its complete semantics and keyboard behavior; prefer a native button for actions or a real link for navigation. Verify accessible name, focus and Enter/Space behavior before delivery.');
    if (/<a\b[^>]{0,800}\bhref\s*=\s*["'](?:#|javascript:void\(0\))["']/i.test(text))
      add('ui-placeholder-navigation', 'A link has a placeholder destination. Connect navigation to the actual destination, or use a button for an action. Exercise the intended interaction; a convincing visual state is not working behavior.');
    // Markup-shape structural cues: need real tags, so they stay quiet on
    // backend scripts and comments. Thresholds favor precision over recall.
    const classAttrs = text.match(/class(?:Name)?\s*=\s*"[^"]*"/gi) ?? [];
    if (classAttrs.filter(a=>/\bcard\b/i.test(a)).length >= 6)
      out.push({key:'ui-card-cluster',skill:'ui-antipattern-review',check:'Six or more card-class enclosures occur in this source. Verify each card earns its container; plain sections, lists or definition rows are often clearer than a grid of lookalike cards. Repeated identical card shapes with thin content are the tell.'});
    const sectionCount = (text.match(/<section\b/gi) ?? []).length;
    if (sectionCount >= 6) {
      const words = text.replace(/<[^>]+>/g,' ').split(/\s+/).filter(Boolean).length;
      if (words / sectionCount < 120)
        out.push({key:'ui-section-sprawl',skill:'ui-antipattern-review',check:`${sectionCount} sections average under ~120 words of visible copy each. Verify every section earns its headline and chrome; merge thin sections into plain flow instead of splitting a small page into visually impressive slices.`});
    }
    const footer = /<footer[\s\S]{0,12000}?<\/footer>/i.exec(text);
    if (footer && (footer[0].match(/<a\b/gi) ?? []).length >= 15)
      out.push({key:'ui-footer-bloat',skill:'ui-antipattern-review',check:'The footer carries 15 or more links. Verify each link earns its place on a site this size; overbuilt footers on tiny sites are decoration, not navigation.'});
    if ((text.match(/<svg\b|<Icon\b|from ['"]lucide|class(?:Name)?\s*=\s*"[^"]*\bicon[-_]/gi) ?? []).length >= 12)
      out.push({key:'ui-icon-density',skill:'ui-antipattern-review',check:'Twelve or more icon markers occur in this source. Verify each icon earns its place beside its heading or sentence; an icon beside everything is decoration that weakens scanning.'});
    if (TOUR.test(text))
      out.push({key:'ui-onboarding-nudge',skill:'ui-ux-principles',check:'A tour, walkthrough or welcome-modal surface is present. Verify the site is not self-explanatory without it; onboarding for obvious interfaces is interruption, not help. If it stays, verify dismiss, resume and reduced-motion behavior.'});
    if (AI_WIDGET.test(text))
      out.push({key:'ui-ai-widget',skill:'product-ui-verification',check:'An AI chat or assistant surface is present. Verify it answers a demonstrated user need rather than riding on availability; a chatbot on a page whose questions a paragraph could answer is insertion, not a feature. If it stays, verify empty, error, rate-limit and keyboard states like any other feature.'});
    // Stylesheet cues need an authorial stylesheet; a script embedding a few
    // declarations (inline styles, CSSOM) cannot establish these patterns.
    if (!ui) return out.slice(0,Math.min(12,Math.max(1,Number.isInteger(limit)?limit:3)));
    if (/\boutline\s*:\s*(?:none|0)\s*[;}]/i.test(text) || /\b(?:outline-none|focus:outline-none)\b/.test(text))
      add('ui-focus-suppression', 'Focus outline suppression was observed. Verify a visible replacement on the rendered control for keyboard users, including forced colors; another stylesheet or utility may supply it.');
    const families = new Set([...text.matchAll(/\bfont-family\s*:\s*([^;}\n]+)/gi)]
      .map(m=>m[1].split(',')[0].trim().replace(/["']/g,'').toLowerCase())
      .filter(f=>f && !/^(?:var\(|inherit$|initial$|unset$|monospace$|ui-monospace$)/.test(f)));
    if (families.size >= 3)
      add('ui-font-competition', 'At least three primary font families occur in this source. Assign a purpose to each; simplify competing display faces and near-identical sans pairings. Keep needed script fallbacks and code fonts. Inspect loaded fonts, long labels, zoom and weight hierarchy; names alone cannot establish a bad pairing.');
    if (/\bfont-size\s*:\s*(?:[1-9]|1[01])px\b/i.test(text) && /\b(?:text-transform\s*:\s*uppercase|letter-spacing\s*:)/i.test(text))
      add('ui-small-tracked-copy', 'Tiny pixel text occurs with uppercase or tracking. Inspect whether labels remain readable at real density, narrow widths and zoom; avoid using tiny uppercase metadata as the default hierarchy.');
    if ((text.match(/\bposition\s*:\s*absolute\b/gi)||[]).length >= 3)
      add('ui-fragile-placement', 'Multiple absolutely positioned elements occur together. Check whether meaningful content depends on fixed coordinates; verify long text, zoom, narrow widths and overlap. Icons and deliberate overlays may legitimately use absolute positioning.');
    // Only explicit opaque hex pairs within one declaration block; never combine
    // values from different selectors or pretend to resolve variables/layers.
    for (const block of text.matchAll(/\{([^{}]{1,1800})\}/g)) {
      const color = /(?:^|;)\s*color\s*:\s*#([\da-f]{6}|[\da-f]{3})\s*(?:;|$)/i.exec(block[1]);
      const bg = /(?:^|;)\s*background(?:-color)?\s*:\s*#([\da-f]{6}|[\da-f]{3})\s*(?:;|$)/i.exec(block[1]);
      if (!color || !bg || /\b(?:opacity|background-image)\s*:|\b(?:color|background(?:-color)?)\s*:[^;]*\b(?:var|rgb|hsl)\(/i.test(block[1])) continue;
      const a=luminance(color[1]), b=luminance(bg[1]), ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);
      if (ratio < 3) { add('ui-low-contrast-pair', `An explicit text/background pair has ${ratio.toFixed(2)}:1 contrast before cascade and compositing. Measure the actual rendered colors and text size; this is below even the 3:1 large-text threshold if applied to ordinary visible text. Verify exceptions and overrides before calling it a violation.`); break; }
    }
    const decorations = [/(?:linear|radial|conic)-gradient\s*\(/i, /backdrop-filter\s*:[^;}\n]{0,120}blur\s*\(/i,
      /(?:box|text)-shadow\s*:/i, /animation(?:-iteration-count)?\s*:[^;}\n]{0,240}\binfinite\b/i,
      /parallax/i, /particles?\b/i, /\bglow\b/i, /mesh-gradient|\borbs?\b|aurora/i];
    if (decorations.filter(re=>re.test(text)).length >= 3)
      out.push({key:'ui-decoration-cluster',skill:'ui-antipattern-review',check:'Several decorative CSS treatments occur together. Inspect the rendered hierarchy against the existing design system and real content; retain effects with a clear purpose and simplify competing emphasis. A branded treatment alone is not a defect.'});
    if ((text.match(/animation(?:-iteration-count)?\s*:[^;}\n]{0,240}\binfinite\b/gi)||[]).length >= 2)
      out.push({key:'ui-continuous-motion',skill:'ui-antipattern-review',check:'Multiple continuous animations were observed. Check attention, interruption and reduced-motion behavior in the complete component; this partial change cannot establish whether safeguards are missing.'});
  }
  if (ui) {
    // Color: stock palette and unsystematic hue sprawl (explicit hex outside
    // custom-property definitions; a token system reuses a few values).
    if (STOCK_PALETTE.test(text))
      out.push({key:'ui-stock-palette',skill:'colors',check:'The default AI-product palette (indigo or violet into purple or pink gradients) occurs. Derive color from this brand and content (logo, photography, existing tokens) as a value ramp with one accent; keep the gradient only if the brand already owns it.'});
    const hexes = new Set((text.replace(/--[\w-]+\s*:[^;}\n]*/g,' ').match(/#(?:[\da-f]{6}|[\da-f]{3})\b/gi) ?? []).map(h=>h.toLowerCase()));
    if (hexes.size >= 12 && (text.match(/var\(--/g) ?? []).length < 3)
      out.push({key:'ui-hue-sprawl',skill:'color-theory',check:`${hexes.size} distinct hard-coded colors occur without custom properties. Define a small token set (ground, surface, text, muted text, accent, states) and reuse it; ad hoc near-duplicates read as unplanned.`});
    // Placement: centered everything loses the reading axis.
    const centered = (text.match(/text-align\s*:\s*center|\btext-center\b/gi) ?? []).length;
    const leftAligned = (text.match(/text-align\s*:\s*(?:left|start)|\btext-(?:left|start)\b/gi) ?? []).length;
    if (centered >= 8 && leftAligned <= 1)
      out.push({key:'ui-centered-everything',skill:'visual-composition',check:`${centered} centered text rules and almost no left-aligned ones. Center only short display lines; body copy, lists, cards and forms read faster on a strong left axis. Check the rendered page for a clear reading line.`});
  }
  if (ui) {
    // Generated-UI ornaments (user-banned): accent rails, dot markers, icon tiles.
    // Utility-class lists are order-free: test each class attribute as a set.
    const classLists = [...text.matchAll(/\bclass(?:Name)?\s*=\s*["'`{]([^"'`}]{1,400})/g)].map(m => ` ${m[1]} `);
    const has = (list: string, re: RegExp) => re.test(list);
    const blocks = [...text.matchAll(/([^{}]{0,200})\{([^{}]{1,1200})\}/g)].map(m => ({selector: m[1].trim(), body: m[2]}));
    const quoteLike = /blockquote|quote|code|pre\b|callout-quote/i;
    const px = (body: string, prop: string) => { const m = new RegExp(`(?:^|;)\\s*${prop}\\s*:\\s*(\\d+(?:\\.\\d+)?)px`, 'i').exec(body); return m ? Number(m[1]) : undefined; };
    const rails = blocks.filter(b => !quoteLike.test(b.selector) && (/(?:^|;)\s*border-(?:left|inline-start)\s*:\s*[2-8]px\s+solid/i.test(b.body)
      || /::?(?:before|after)/.test(b.selector) && /position\s*:\s*absolute/i.test(b.body) && (px(b.body, 'width') ?? 99) <= 6 && /(?:top\s*:\s*0[^;]*;[^}]*bottom\s*:\s*0|height\s*:\s*100%)/i.test(b.body))).length
      + classLists.filter(list => has(list, /\sborder-l-(?:2|4|8|\[\dpx\])\s/) && has(list, /\sborder-(?:[a-z]+-)?\d{2,3}(?:\/\d+)?\s/)).length;
    if (rails)
      out.push({key:'ui-accent-rail',skill:'anti-ai-slop',check:'A colored left rail (border-left or a pseudo-element bar) accents a card or panel. This is a stock generated-UI ornament; remove it and group with spacing, headings or a real surface change. Keep a rail only where it encodes a distinct state the user needs (and then pair it with text).'});
    const dots = blocks.filter(b => { const w = px(b.body, 'width'), h = px(b.body, 'height'); return w !== undefined && h !== undefined && w >= 4 && w <= 14 && Math.abs(w - h) <= 2 && /border-radius\s*:\s*(?:50%|100%|9{3,}px|\d{2,}px)/i.test(b.body) && /background(?:-color)?\s*:/i.test(b.body); }).length
      + classLists.filter(list => has(list, /\s(?:size|[wh])-(?:1\.5|2|2\.5|3)\s/) && has(list, /\srounded-full\s/) && has(list, /\sbg-[a-z]/)).length;
    if (dots)
      out.push({key:'ui-dot-marker',skill:'anti-ai-slop',check:'A small colored dot (often glowing) is styled as a marker before labels, chips or list items. This is a stock generated-UI tell; remove it. Keep a dot only for a real, changing state with an accessible text equivalent.'});
    const tiles = blocks.filter(b => { const w = px(b.body, 'width'), h = px(b.body, 'height'), r = px(b.body, 'border-radius'); return w !== undefined && h !== undefined && w >= 24 && w <= 72 && Math.abs(w - h) <= 2 && r !== undefined && r >= 4 && /(?:display\s*:\s*(?:inline-)?(?:flex|grid))/i.test(b.body) && /(?:place-items|align-items|justify-content)\s*:\s*center/i.test(b.body) && /(?:background|border)\s*:/i.test(b.body); }).length
      + classLists.filter(list => has(list, /\s(?:size|h)-(?:8|9|10|11|12|14)\s/) && has(list, /\srounded-(?:md|lg|xl|2xl)\s/) && has(list, /\s(?:items-center|place-items-center|justify-center)\s/) && has(list, /\s(?:bg|border)-[a-z]/)).length;
    if (tiles)
      out.push({key:'ui-icon-tile',skill:'anti-ai-slop',check:'An icon is wrapped in a tinted or bordered rounded tile (icon badge). This is a stock generated-UI ornament; show the icon plainly at text size, or drop it when the label already carries the meaning.'});
  }
  if (ui || prose) {
    // Order: the stock landing sequence, section by section. Headings only.
    const headings = [...text.matchAll(/<h[1-3]\b[^>]*>([\s\S]{0,160}?)<\/h[1-3]>|^#{1,3}\s+(.{1,160})$/gim)].map(m=>(m[1] ?? m[2] ?? '').replace(/<[^>]+>/g,' '));
    const families = TEMPLATE_SECTIONS.filter(re=>headings.some(h=>re.test(h))).length;
    if (families >= 4)
      out.push({key:'ui-template-sequence',skill:'anti-ai-slop',check:`Section headings follow the stock landing template (${families} of trusted-by, features, how-it-works, testimonials, pricing, FAQ, final CTA). Order sections by this product's own argument: the one thing it does, proof specific to it, the action. Drop sections that exist only because templates have them.`});
  }
  if (prose) {
    const stock = [/\bin today.s (?:fast.paced|rapidly evolving|digital)\b/i,/\bunlock (?:the |your )?(?:full |true )?potential\b/i,/\bseamless(?:ly)?\b/i,/\brevolutionary\b/i,/\bcutting.edge\b/i,/\ball.in.one (?:solution|platform)\b/i];
    if (stock.filter(re=>re.test(text)).length >= 3)
      out.push({key:'prose-stock-cluster',skill:'natural-editorial-writing',check:'Several stock promotional phrases occur together. Replace unsupported generalities with specific behavior and reader value, preserving the requested voice and required wording. This is not evidence of AI authorship.'});
    if (/\blorem ipsum\b/i.test(text))
      out.push({key:'placeholder-copy',skill:'anti-ai-slop',check:'Placeholder copy was observed. Before delivery, confirm whether a mockup was requested; otherwise use supplied content or clearly disclose missing facts. Never invent testimonials, customers or performance numbers to fill space.'});
    // Reader-visible text only: front matter, inline code, link targets and
    // embedded script/style are not copy, and hrefs are not claims.
    const visible = text.replace(/^---[\s\S]*?\n---(\n|$)/,'').replace(/`[^`\n]*`/g,' ')
      .replace(/https?:\/\/\S+/g,' ').replace(/(?:href|src)\s*=\s*"[^"]*"/gi,' ')
      .replace(/<(?:script|style)[\s\S]*?<\/(?:script|style)>/gi,' ');
    const inDocs = DOCS_PATH.test(file);
    const policyPage = POLICY_FILE.test(file);
    const push = (key: string, skill: string, check: string) => out.push({key,skill,check});
    if (!inDocs) {
      const weakHits = new Set(LEAK_WEAK.filter(w=>wordRe(w).test(visible))).size;
      if (LEAK_STRONG.test(visible) || DESIGN_LEAK.test(visible) || weakHits >= 2)
        push('prose-implementation-leak','copywriting','Implementation names (frameworks, hosting, repositories, pipelines, schemas, design-system internals) occur in reader-facing copy. Keep such names only on pages that document those subjects (docs, changelog, status); cut stack badges and backstage names from marketing and product pages. Verify each remaining name serves the reader\u2019s purpose in that context.');
      if (TRANSPARENCY_HEADING.test(visible))
        push('prose-transparency-section','copywriting','A section heading narrates the site itself (how it works, its process, its architecture). Cut it unless this page exists to document those subjects; readers came for the outcome, not the backstage tour. Link to the docs instead of inlining the tour.');
      if (AI_PROVENANCE.test(visible))
        push('prose-ai-provenance','copywriting','An AI-provenance claim occurs (AI-powered, AI-assisted, AI-generated). Keep it only when the reader chose this product for AI; otherwise it is clutter about production, not value. Describe the capability, not how the words were made.');
    }
    if (new Set(BUZZWORDS.filter(w=>wordRe(w).test(visible))).size >= 4)
      push('prose-buzzword-stack','natural-editorial-writing','Four or more promotional buzzwords occur together. Replace stacked adjectives with one specific, verifiable claim each; buzzword density reads as generated even when every word is true.');
    if (SELF_PRAISE.test(visible))
      push('prose-self-praise','copywriting','Self-congratulatory copy occurs (careful, thoughtful, elegant or beautiful craft claims). Cut praise of the work itself; demonstrate the quality in the content and let the reader conclude it.');
    if (!inDocs && !policyPage && THEATER.test(visible))
      push('prose-theater-claim','copywriting','A trust-theater claim occurs (privacy-by-design, military-grade, WCAG badge, HTTPS reassurance). Prefer doing the thing over advertising it; keep such claims only where the reader decides on them (security page, plan comparison, policy document).');
    if (MISSION.test(visible))
      push('prose-mission-speak','copywriting','Manifesto language occurs (mission, revolutionize, democratize, the future). Verify the scale warrants it; small practical sites state what they do and for whom instead of inventing a philosophy.');
    let metricBare = false;
    for (const match of visible.matchAll(/\b\d+(?:\.\d+)?\s*x\b|\b\d{2,3}%\s+(?:faster|smarter|better|cheaper|more \w+|accurate|efficient)\b/gi)) {
      const at = match.index ?? 0;
      if (!METRIC_BASIS.test(visible.slice(Math.max(0,at-300),at+match[0].length+300))) { metricBare = true; break; }
    }
    // Chatbot prose tells, measured by the shared prose checker (stock
    // phrases, em-dash density, triads, repeated openers) on real copy only.
    if (!inDocs) {
      const report = proseReport(visible.replace(/<[^>]+>/g,' '));
      const tells = report.words >= 120 ? report.findings.filter(f=>['stock-phrase','dash-density','rule-of-three','repeated-opener','boilerplate-heading'].includes(f.rule)) : [];
      if (tells.length >= 3)
        push('prose-ai-tells','natural-editorial-writing',`Generated-sounding prose patterns: ${[...new Set(tells.map(f=>f.message))].slice(0,4).join(' · ').slice(0,420)}. Rewrite in the product's own voice with concrete specifics.`);
    }
    if (metricBare)
      push('prose-metric-theater','copywriting','A performance multiple or percentage claim occurs without a nearby basis (measured where, on what, against what). Add the basis or cut the number; unsupported precision reads as invented even when it is real.');
    const navLabels = new Set<string>();
    for (const re of [new RegExp(`<(?:a|Link|NavLink)\\b[^>]*>\\s*(${VAGUE_NAV_LABEL})\\s*<`,'gi'),new RegExp(`\\[(${VAGUE_NAV_LABEL})\\]\\([^)]*\\)`,'gi')])
      for (const m of visible.matchAll(re)) navLabels.add(m[1].toLowerCase());
    if (navLabels.size >= 2)
      push('prose-vague-nav','copywriting','Two or more navigation labels are vague (Insights, Discover, Explore, Solutions, Resources). Name each destination specifically; generic labels force every visitor to click to learn what lives there.');
  }
  return out.slice(0,Math.min(12,Math.max(1,Number.isInteger(limit)?limit:3)));
}
