// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update
import values from "./data/meta.json" with { type: "json" };
import { flattenModelCatalog } from "../model-catalog.js";
export const META_MODELS = flattenModelCatalog("meta", values);
