// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update
import values from "./data/stepfun-step-plan.json" with { type: "json" };
import { flattenModelCatalog } from "../model-catalog.js";
export const STEPFUN_STEP_PLAN_MODELS = flattenModelCatalog("stepfun-step-plan", values);
